shadowsocks/shadowsocks-libev

- README.md
Fedora 19 is officially end of life.
> no more fedora 19 updates now.

- src/jconf.c
- src/jconf.h
- src/server.c
Changes:
* Use the `nameserver` in the configuration file if any.
* Use Google Public DNS only if the user does not nominate a nameserver.
Rationale:
Servers usually have _caching_ DNS resolvers like `dnsmasq` and `unbound`. It will be waste of resources if every query is sent to Google Public DNS.
Issues:
* Currently, only one `nameserver` can be specified in the configuration file.
* I am not sure what your intent is when you fall back to the system-wide configuration if the second parameter (`nameservers`) of `resolv.c:resolv_init` is `NULL` even if it can never be (because Google Public DNS is added anyway).
* I am too lazy to update supporting documents like `README`...
> Refine nameserver settings

- src/server.c
Listen on all IP address (ipv4 and ipv6 dual mode) in single bind by default if not specify '-s' or in config file.
Create an IPv6 server socket that can also accept IPv4 connections. To do so, create a regular IPv6 socket, turn off the socket option IPV6_V6ONLY, bind it to the "any" address, and start receiving. IPv4 addresses will be presented as IPv6 addresses, in the IPv4-mapped format.
> Dual mode IPv4/IPv6 stack support

- debian/shadowsocks-libev.init
run as root firstly, then switch to $USER by "-a" parameter, so that we can bind to port lower than 1024 when running as normal user.
> update debian init script

- src/jconf.c
in wiki https://github.com/shadowsocks/shadowsocks/wiki/Configuration-via-Config-File the format of config is
```
{
"server":"my_server_ip",
"server_port":8388,
"local_address": "127.0.0.1",
"local_port":1080,
"password":"mypassword",
"timeout":300,
"method":"aes-256-cfb",
"fast_open": false
}
```
i think it's better to compatible with that.
> fixed config.json compatibility issue

- debian/shadowsocks-libev.init
wrong spelling of 'socks5' in shadowsocks-libev.init
> Fix wrong typo in init.d script

- rpm/SOURCES/etc/init.d/shadowsocks-libev
here is also a wrong spelling...
> Fix typo in init.d script under rpm directory

- debian/shadowsocks-libev.init
- openwrt/Makefile
- shadowsocks-libev.8
- shadowsocks-libev.pc.in
There are several words written as 'scoks5' in the repo and I believe that they should be 'socks5'.
> Change 'scoks' to 'socks'

- src/encrypt.c
Based on commit: https://github.com/ARMmbed/mbedtls/commit/ac50fc5e2ffcc28a3150f643f5696199f3b18e07
> Fix typo in encrypt.c

- shadowsocks-libev.pc.in
Currently shadowsocks-libev.pc.in seems to be invalid and was warned by lintian when trying to build deb package:
E: shadowsocks-libev: pkg-config-bad-directive usr/lib/x86_64-linux-gnu/pkgconfig/shadowsocks-libev.pc Cflags: -L${libdir} -lshadowsocks -lcrypto
So I corrected it and now it seems to be working.
> Fix mistake in pkgconfig .pc file

- debian/autopkg.sh
To ignore VCS directory in dpkg-source.
> fix debian pkg script

- Makefile.am
- configure.ac
- debian/README.Debian
- debian/copyright
- debian/libshadowsocks1.symbols
- debian/rules
- debian/shadowsocks-libev-local@.service
- debian/shadowsocks-libev-redir@.service
- debian/shadowsocks-libev-server@.service
- debian/shadowsocks-libev-tunnel@.service
- src/Makefile.am
* Added several systemd service templates for `ss-server`, `ss-redir`, `ss-local` and `ss-tunnel` from downstream Archlinux AUR, which may benefit advanced users to cooperate better with systemd.
* Added a configure-time option into autotools scripts which allows user to use system-proviced `libsodium`, `libev` and `libudns` instead of the static-linked one. Considering that `shadowsocks-libev` is used widely in lower-end devices which requires binaries to be build with static libraries, this option is still made optional and only for advanced users or downstream Linux distribution package maintainers.
* I didn't find `libcork` and the so-called `libipset` in Debian and most of the distributions, so they are kept and some copyright information was added into `debian/copyright`.
> Add service templates and a option to build against system shared libs

- configure.ac
Don't configure libsodium when using system libs since it would be a waste of time.
P.S: Please update configure scripts using `autoreconf`, thanks.
@madeye
> don't configure libsodium when using system libs

- src/local.c
- src/server.c
1. The error fixed by  e7a1d1e3337708567d3b8edee34471d90e9dbfe6 also exist in server.c
2. Use connectx to send first package will return error EINPROGRESS in local.c, but the same code work in server.c
However, with this commit, ss-local with fastopen on Darwin still can't work completely. HTTP request can get right reponse, but the data sent in first package will be sent again.
I think there still be error like `if (s < server->buf->len)`
I'm sorry for insufficient test in last pull request.
> fix two error

- src/encrypt.c
> use sha1_hmac function directly for PolarSSL

- src/encrypt.c
- src/encrypt.h
Note:
- ChaCha20 with an extended (96 bit) nonce and a 32-bit counter has
been implemented as crypto_stream_chacha20_ietf() from LibSodium 1.0.4
- The name of new cipher is "chacha20-ietf"
> add IETF-compatible Chacha20 cipher support

- src/manager.c
without checking, segmentation fault will happen when received data only contains **white-space characters**.
> add check to avoid Segmentation fault

- src/manager.c
If received data is invalid, this method can cause memory leak.
> Fix to avoid memory leak.

- src/local.c
- src/server.c
Sometime, ss-local.exe will crash while exiting. Root cause is that close_and_free_server will free the memory of server_t which contains cork_dllist_item (referenced by pointer curr). After that, the next iteration will use the curr->next to get the next item, but at this point the memory pointed by curr has been freed.
> Fix the crash issue in free_connections

- docker/alpine/README.md
Two URLs is incorrect in `docker/alpine/README.md`.
> fix wrong URLs in docker/alpine/README.md

- src/redir.c
When an OpenWRT router is connected to the Internet via multiple NAT, it's likely that the TCP connections to the remote Shadowsocks server will fail after a few minutes of inactivation without the clients being noticed.  A typical case is that when a LAN user browses google.com for the first time and then browse it again a few minutes later, the browser will reuse the previously established connection which is no longer available and not closed by the router(not even a broken pipe signal is triggered), resulting in connection timeout and the browser reconnecting. To make the remote connections live longer and automatically close broken connections, enabling TCP keep-alive does the trick. I have tested this fix and it works pretty well.
> Enable TCP keep-alive feature for remote connections

- libipset/bdd/write.c
- src/encrypt.c
- src/jconf.c
- src/json.c
- src/local.c
- src/netutils.c
- src/netutils.h
- src/udprelay.c
code issues found by Clang with
CFLAGS="-Os -Wall -Wextra -Werror=unused-const-variable -Wno-error=unused-parameter"
enabled
The details as follows:
- variable initialization issue, modified them as Clang suggested
- data type mismatch when comparing, fix them either by casting or changing
the data type of index of iterator
- get_sockaddr() in netutils may return -1 thus changed returning type from
size_t to ssize_t, which makes Clang happier
- recvfrom() in udprelay is identical, fix this by creating local variable
for comparison  and assign back to buf->len when returning value is acceptable
> Polish code

- src/netutils.c
- src/netutils.h
- src/udprelay.c
This may fix #565
It is not recommended to compare two structs via memcmp although they have been
memset to 0.
Added two helper functions to compare sockaddr_storage, one for address only and
the other one takes port into account.
These two functions are based on Unbound version in util/net_help.c, and
comform needs of shadowsocks-libev.
经过自己的服务器测试，发现原来基本全部miss的有大概率变为hit
> Fix sockaddr comparison

- src/udprelay.c
The whole remote_ctx is inserted into the cache and sockaddr_storage contains
both address and port.
> compare port as well

- src/local.c
- src/manager.c
- src/redir.c
- src/server.c
- src/tunnel.c
- src/utils.c
errno is never set to zero by any system call or library function,
and it's programmer's resposibility to reset it before doing checks.
Otherwise the error might be misleading.
> Reset errno to 0 before checking it

- configure.ac
This is an option in the origin configure script, add this to configure.ac to generate
config.h since submodules are sharing the same file.
All checks needed are guaranteed, thus simply add it to the ending of file.
> libudns: add definition to enable IPv6 support

- src/cache.c
- src/encrypt.c
- src/jconf.c
- src/json.c
- src/local.c
- src/manager.c
- src/mm-wrapper.h
- src/redir.c
- src/resolv.c
- src/server.c
- src/tunnel.c
- src/udprelay.c
- Added one macro to avoid dangling pointers
- Added two functions to perform NULL pointer check
since the allocation is not guaranteed by C library, although it
is a rare case, just for sanity
- Add NULL pointer check to brealloc() and bfree() and for sanity as well
> Refine memory management

- src/redir.c
redir.c:212:9: error: format ‘%ld’ expects argument of type ‘long int’, but argument 5 has type ‘ssize_t’ [-Werror=format=]
LOGI("redir to %s:%d, len=%ld", ipstr, port, r);
^
> Fix compile on 32-bit machine

- man/shadowsocks-libev.8
- man/ss-local.1
- man/ss-manager.1
- man/ss-redir.1
- man/ss-server.1
- man/ss-tunnel.1
- added option '-w'
- added -d, --fast-open, --acl into ss-manager's man page
- removed -l from ss-server's man page
- removed -p, -l, -b from ss-manager's man page
- changed '-n nofile' => '-n number' for read easy
- fixed default timeout value (10 => 60)
- fixed 80 char width
> manpage updates

- src/encrypt.c
Close #603
After use, sensitive data should be overwritten, but memset() and hand-written code can be silently stripped out by an optimizing compiler or by the linker.
The sodium_memzero() function tries to effectively zero len bytes starting at pnt, even if optimizations are being applied to the code.
> use sodium_memzero() to clear sensitive data

- src/local.c
- src/server.c
before,
``` yyyy-mm-dd HH:MM:SS INFO: connect to 2001:b28:f23f:f005::a:443```
after fixed,
``` yyyy-mm-dd HH:MM:SS INFO: connect to [2001:b28:f23f:f005::a]:443```
> fixed ipv6 address format in log message

- Changes
Just a proposal, you may have better solution.
Due to a warning of lintian: no-upstream-changelog
(refer: https://mentors.debian.net/package/shadowsocks-libev)
In short: upstream should have changelog in source tarball, instead of a symbolic link to debian/changelog
> Make Changes independent to debian/changelog

- src/Makefile.am
- src/cache.h
- src/jconf.h
- src/local.h
- src/win32.h
Including inconsistency in `src/Makefile.am` and minor typo in comments.
> Fix typo in source code

- .gitignore
- debian/.gitignore
- debian/control
`libshadowsocks-libev-dev` should depend on `libshadowsocks-libev1`, not `libshadowsocks1`.
> Another fix for #668 to solve dependency problem

- src/local.c
- src/shadowsocks.h
Added a signal SIGUSER1 as parent thread can stop the server by sending this signal. 
This operation is thread-safe which require in ShadowsocksX-NG, a MAC OS X version port.
Reference:
https://github.com/cs17899219/ShadowsocksX-NG/blob/develop/ShadowsocksX-NG/SSLocalManager.c
> Add a signal SIGUSR1 for safely stop the server

- debian/control
- debian/copyright
- debian/libshadowsocks-libev1.install
- debian/rules
- debian/shadowsocks-libev.init
- debian/shadowsocks-libev.install
- debian/shadowsocks-libev.postinst
- debian/watch
[v2: too add debian/shadowsocks-libev.postinst file]
A few itmes deserve to be mentioned:
- use apg to generate random password when install.
- generated password won't get updated when upgrading / reinstall.
- add more to description to make lintian happy.
- generated Makefile.am don't need to be listed in debian/copyright.
- the way of installing systemd service is changed. Thanks to advice
from Boyuan.
- multi-arch can be archived without specific setting in debian/rules
- add debian/watch file
> Sync debian/ folder

- debian/shadowsocks-libev.postinst
Missing slash causes dpkg -i to fail:
```
Setting up shadowsocks-libev (2.4.7-1) ...
sed: can't read etc/shadowsocks-libev/config.json: No such file or directory
dpkg: error processing shadowsocks-libev (--install):
subprocess installed post-installation script returned error exit status 2
```
> fix path typo in debian/postinstall

- man/shadowsocks-libev.8
- man/ss-local.1
- man/ss-manager.1
- man/ss-nat.1
- man/ss-redir.1
- man/ss-server.1
- man/ss-tunnel.1
Make license of man pages to DFSG-free, according to:
- https://wiki.debian.org/DFSGLicenses
- https://wiki.debian.org/qa.debian.org/gfdlinvariant
> relicense manpages to GFDL with no invariant sections

- .gitignore
- src/common.h
- src/jconf.c
- src/jconf.h
- src/local.c
- src/manager.c
- src/server.c
- src/tunnel.c
Add some new jconf parameters:
jconf name | valid values | equivalent 
---------- | -------------- | ----------
tunnel_address | socket address | "-L" of ss-tunnel |
mode |  "tcp_only", "tcp_and_udp" or "udp_only" | "-U" and "-u" options of server/tunnel/manager |
With these new jconfs, ss-tunnel can work with json config files, without using command line parameters
And add project vimrc to gitignore, as the coding indent is quite different from kernel.
> New jconf parameters

- src/netutils.c
- src/server.c
when I use ss-server  with "-b x.x.x.x", sometimes I got the below errors,
connect: cannot assign requested address
bind_to_address: Address already in use
try to fixed it
> fix bugs with when ss-server bind_address enabled

- .gitignore
otherwise someone copy the repo from local computer and add to other repo as depend source , will encounter:
No rule to make target 'ss-nat', needed by 'all-am'.  Stop.
or someone has mod src/ss-nat , git can not detect the modify.
to reproduce this error:
git clone https://github.com/shadowsocks/shadowsocks-libev.git
cd my_exist_repo
cp -rv ../shadowsocks-libev ./
rm -rf ./shadowsocks-libev/.git
git add ./shadowsocks-libev  #now the src/ss-nat will silently be ignored ...
> src/ss-nat should be excluded from rule src/ss-* in .gitignore

- openwrt/Makefile
Debloating asciidoc and xmlto makes life easier on OpenWrt/LEDE.
> openwrt: disable documentation build by default

- docker/ubuntu/README.md
It took me a lot of time to setup DNS tunnelling in OpenWrt, because I didn't know that I have to open the UDP port in docker. I hope adding this example can help others.
> Update docker README

- src/netutils.h
MPTCP_ENABLED value changed from 26 to 42 because upstream kernel v4 introduced new TCP_CC_INFO constant which takes MPTCP_ENABLED's old value 26.
> Add backward compatibility for MPTCP_ENABLED

- src/utils.c
- src/utils.h
It's help to identify statically compiled files. 
$ ss-local -h
shadowsocks-libev 2.5.3 **with mbed TLS 2.2.1**
>  Show crypto library using in the help message

- libcork/pthreads/thread.c
- The usage of `pthread_setname_np` is not supported on versions of
glibc earlier than 2.12. This patch checks the glibc MINOR version and
only uses that API where supported.
- This will suppress undeclared function warning when compiling
with uClibc/musl-libc.
> libcork: use API where supported

- rpm/SPECS/shadowsocks-libev.spec
Update SPEC file to install /debian/shadowsocks-libev-*.service files.
> Include shadowsocks-libev-*.service files for RPM package

- README.md
ss-libev is now available in Debian 9+ and Ubuntu 16.10+.
> Add instruction to install from official deb repo

- configure.ac
- rpm/SPECS/shadowsocks-libev.spec.in
It seems to me that the spec file misses some build dependencies, such as `xmlto` and `asciidoc`.
I complemented them so that we can install all build dependencies by running `yum-builddep shadowsocks-libev.spec`.
Furthermore, I'd like to make `configure` procedure fail if those two package are missing.
> Fix missing dependencies

- rpm/genrpm.sh
1. Remove function `get_att_val`:
That function uses `eval` to set default values for bash variables.
Because it is very dangerous to use `eval` (someone call it the plague of shell scripting), I'd like to use the bash builtin to do that.
2. Double quote all variables to avoid unexpected expansion when using it.
BTW, the default version of `git` on EL6 is too old to support archive in `.tar.gz` command. Maybe we can change the default format to `tar`?
> Make genrpm.sh a little safer.

- docker/alpine/Dockerfile
According to [documentation](https://github.com/shadowsocks/shadowsocks-libev/blob/master/doc/ss-server.asciidoc) `-U` option enables UDP relay and disables TCP relay. 
TCP relay shouldn't be disabled by default, as it may mislead those who are referencing official Dockerfile.
> Remove -U option that disables TCP relay

- src/local.c
Before,
```bash
$ ss-local -s::1 -p8388 -b::1 -l1080 -k123456 -v
...
2016-10-25 20:07:03 INFO: listening at ::1:1080
...
```
After,
```bash
$ ss-local -s::1 -p8388 -b::1 -l1080 -k123456 -v
...
2016-10-25 20:07:49 INFO: listening at [::1]:1080
...
```
> Friendlize init message while listen on an IPv6 address.

- doc/shadowsocks-libev.asciidoc
- src/jconf.c
- src/jconf.h
- src/server.c
I'm very glad to see that ss-server not supports `-6` option in the command line to prefer IPv6 traffic on the server side.
Would you consider adding `ipv6_first` option to the config file? This patch may help.
Thanks.
> support ipv6_first option in config file

- src/acl.c
Using `iptables --version` to perform permission check on operating iptables is insufficient.
For example, running in a child Linux user namespace or in a Docker container.
Let's just simply use `iptables -L` instead.
> fix permission check on operating iptables

- src/local.c
- src/manager.c
- src/redir.c
- src/server.c
- src/tunnel.c
For security reasons we may abort execution if specified running user does not exist (or it will run as root unexpectedly).
And warn users if running as root.
> exit if attempting run as nonexistent user and warn if running as root

- src/jconf.c
- src/utils.c
This patch fixes:
1. a memory leak
2. wrong value when the type of an option mismatches
3. missing null pointer check in ss_strndup
> Fix config file parsing 

- configure.ac
The following error will occur when configuring with --enable-system-shared-lib:
```
/usr/bin/rm: cannot remove 'libtoolT': No such file or directory
```
This issue is caused by overwriting gnu make variable `RM` with `rm`,
whose default value is `rm -f` (https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html).
> Fix broken `configure --enable-system-shared-lib`

- rpm/SPECS/shadowsocks-libev.spec.in
Traditionally, `*.la` and `*.so` should go towards `*-devel` package while `*.so.VERSION` should go towards the main package, even if `*.so` in current version is almost useless :smile:
> RPM packaing: move .la, .so  to devel subpackage

- rpm/SPECS/shadowsocks-libev.spec.in
Tests show that EL6 is too old to support `%elif` statement (which is very stupid).
And revert dependency `openssl-libs` to `openssl` because of
inconsistent names in EL6.
> fix broken EL6 packaging support

- src/utils.c
> revert `pwd->name` to `user` when error occurs

- src/json.c
- src/local.c
- src/redir.c
- src/server.c
- src/tunnel.c
- src/udprelay.c
- GNU treats void* as char* when doing pointer arithmetic, so let's make it clear
- Fix memory leak, save copy from malloc() and pass the original pointer to free()
- minor type mismatches
> Fix issues found by cppcheck

- src/local.c
No behavior changes but one can see more clearly what is going on. Probably runs faster when a host rule is matched.
> Refine ACL logic in local.c

- src/acl.c
I don't think `#` will be a legal character in non-comment usages.
> Add support for comments in the middle of the line in ACL files

- src/Makefile.am
- src/Makefile.in
- src/manager.c
- src/manager.h
1. ss-manager will try to bind needed port to check its availability;
2. echo "ok" to normal request;
3. echo "port is not available" back when port used by other process.
I am not so farmiliar with pure c and libev, please point out anything improper and I will fix it soon.
> Check port before add port via ss-manager

- debian/shadowsocks-libev.postinst
setcap setting is only for configure/reconfigure case in postinst script
> debian/shadowsocks-libev.postinst: Limit capabilities setting

- m4/mbedtls.m4
Per Felix Fietkau's request in https://github.com/lede-project/source/pull/657
> mbedtls: Make rc4, camellia, blowfish cipher checks optional

- src/plugin.c
Info:
- https://www.gnu.org/software/hurd/community/gsoc/project_ideas/maxpath.html
- https://www.gnu.org/software/hurd/hurd/porting/guidelines.html#PATH_MAX_tt_MAX_PATH_tt_MAXPATHL
Quote:
when the __GLIBC__ macro is defined, getcwd() calls can be just
replaced by get_current_dir_name() calls.
> Fix FTBFS of PATH_MAX on GNU/Hurd

- README.md
SHADOWSOCKS_MARK is used at line #405 and #410, but never created.
> Create SHADOWSOCKS_MARK in iptable rules

- .travis.yml
The shared lib file, libsodium.so, could not be found in default share object file path.
The default libsodium.git install files into /usr/local/lib, which is NOT found by system defaults.
> fix shared lib search path issue

- debian/control
- debian/copyright
Use asciidoc as Build-Depends, because user may build under Wheezy
or Ubuntu 14.04.
> Sync debian/ folder with debian version 2.6.2+ds-1

- src/encrypt.c
crypto_stream_chacha20_ietf_xor_ic() was first available when libsodium was bumped to version major 8. Debian jessie still uses major 7 minor 2, so check SODIUM_LIBRARY_VERSION_MAJOR and keep backward compatibility.
With this patch, user does not need to build his own libsodium from source, they can simply use Debian's libsodium-dev package.
> libsodium version checking with crypto_stream_chacha20_ietf_xor_ic()

- doc/ss-local.asciidoc
- doc/ss-manager.asciidoc
- doc/ss-redir.asciidoc
- doc/ss-server.asciidoc
- doc/ss-tunnel.asciidoc
- src/local.c
- src/plugin.c
- src/plugin.h
- src/redir.c
- src/server.c
- src/tunnel.c
Now shadowsocks-libev should support obfsproxy standalone(proxy) mode now.
The overall idea is pretty simple and stupid, just run obfsproxy using given address/port.
Since we have standalone mode, no environment nor protocol is really needed, just make ss-server/local to listen/connect to a localhost port.
That's all.
I tested it with both obfs3 and screamblesuite(need extra --password) and they both work fine in my test environment.
I also fixed one doc bug, which for command line --plugin_opts is wrong, but --plugin-opts.
However, since this implementation needs to co-exist with the SS protocal one, I detect the plugin name and only when it's "obfsproxy" it will go through the obfsproxy parameter assembly routine.
For others plugin, it still follow the old SS_* environment way.
For me, …
> Obfsproxy standalone mode

- README.md
1. Steps about "build and install the latest mbedTLS" have a mistake. With these steps, the output file is *.a, static library, instead shared library.
2. No need to install libmbedtls and libsodium from repository, because they're built from latest source.
3. dh-autoreconf is needed when building deb on Debian/Ubuntu.  See #1174
> Update readme about libmbedtls and libsodium

- README.md
With the `--no-install-recommends` option, `apt` command will not install `automake` package automatically as recommended package of `autoconf`. So it should be installed clearly.
> fixed missing apt pkg: automake

- README.md
- debian/README.Debian
- debian/control
- debian/rules
This would fix #1198 and make .deb packaging only suitable for Ubuntu 16.04 or higher.
> Fix building on Ubuntu 16.04; various document update

- doc/ss-manager.asciidoc
- doc/ss-server.asciidoc
Some more update in ss-manager and ss-server docs. Hope that my understanding is correct.
> Clarify port_password usage in docs

- scripts/deb4trusty.sh
- scripts/deb4xenial.sh
For trusty, debhelper is 9, so need to add the Build-Depends
for the build script.
With a few other fixes for trusty script.
> dh-systemd dependency should be removed for debhelper >=10

- src/aead.c
- src/stream.c
This is useful when checking connection issues, and can be used to
check broken random number generator and replay attacks.
> Output error log when repeat IV/salt detected

- scripts/iperf.sh
Wait for iperf server to receive all data.
One second should be enough in most cases.
> iperf.sh: wait one second before killing processes

- README.md
mk-build-deps is provided by devscripts package, and also relies on
equivs package.
> README: Install build dependencies by mk-build-deps cmd

- scripts/deb4trusty.sh
- Move Build-Depends dh-autoreconf dh-systemd to debian/control
- Also change debian/compat to 9 (debhelper 9)
> Update trusty build script

- scripts/deb4xenial.sh
Because user may upgrade from previous LTS version, xenial-backports
is better to be added by us for safety.
And use debhelper 10 for shadowsocks-libev only.
> Add xenial-backports repository

- rpm/SPECS/shadowsocks-libev.spec.in
- rpm/genrpm.sh
* auto select latest version;
* bash-completion comes with version 2.6.0;
* version greater than 2.6.2 need submodules packed;
**TODO**
> genrpm changes

- src/redir.c
- src/redir.h
- src/utils.c
给 ss-redir 增加了 TFO 支持。
当 ss-redir 接受客户端的连接后，会等待 5ms 让客户端发送数据（例如 HTTP 请求），让这个数据能带在 SYN 中发给 ss-server。这样就能做到在 1-RTT 中完成整个 HTTP 请求与响应（也包括将来的 TLS1.3）。
> Add tcp-fast-open support for ss-redir

- rpm/SPECS/shadowsocks-libev.spec.in
- rpm/genrpm.sh
Here are the problems existing in the old RPM packaging scripts:
1. The old `genrpm.sh` is designed to build RPMs for all versions of
shadowsocks-libev with an option '-v'.
This increases the complexity because we need to keep it compatible
with old versions.
2. I have to modify the script manually in order to build RPMs from
non-release commit or dirty workspace.
The new script will only build RPMs and SRPMs from current workspace,
not commit.
The version-release number will be determined automatically from the
`git describe` command.
> Rewrite genrpm.sh to build RPM from current Git workspace

- .gitignore
- m4/sodium.m4
- rpm/SPECS/shadowsocks-libev.spec.in
- rpm/genrpm.sh
1. add missing build and runtime dependencies
2. change minimal version requirement for libsodium to 1.0.4, which
should work fine with ss-libev and EPEL7 users will not have to compile a
later version.
3. add more entries to .gitignore
> fix rpm SPEC file

- src/local.c
- src/netutils.h
- src/redir.c
- src/server.c
- src/tunnel.c
According to mptcp developers the best way to make mptcp application kernel indepedant is to test MPTCP_ENABLED values from the newest to the oldest.
- Replace defined MPTCP_ENABLED value by an array of all known values ended by a 0.
- If MPTCP_ENABLED value is defined at compile time fill the array with only this value.
- Reuse mptcp var to store the real value of the discovered kernel value.
- Mptcp var value of 1 mean to discover the value from the kernel whereas >1 mean that the value is already known/discovered and can be used as it. if mptcp var is 0 then mptcp is not supported by the kernel.
Further improvements : 
- listener->mptcp from ctx should be a pointer to the main common mptcp var to be able to report the discovered kernel value to future remote connections.
> mptcp: make shadowsocks kernel independant

- debian/control
- debian/shadowsocks-libev.postinst
I prefer to use `pwgen` and it is already installed in my system. Allow using `pwgen` as the password generator so I'm not forced to install `apg`.
> Allow the use of pwgen to generate passwords

- configure.ac
- src/jconf.c
- src/jconf.h
- src/redir.c
- src/redir.h
- src/server.c
- src/server.h
As IP headers are not reachable by application from the socket user-space, we need a workaround to pass the TOS value from local traffic to the outgoing ciphered traffic and then apply some traffic control rules based on the IP TOS value. 
ss-server:
This patch, allows you to set a TOS/DSCP value to the outgoing ciphered connections to the client from a netfilter mark setted to the (re)comming connection from the outside world. TOS/DSCP value is extracted from the 16 bits mark with a mask on the lower bits, upper bits of the mask must be set to 0xDC (ex: a mark with value 0xDC08 will set a TOS/DSCP of 0x08 to the ciphered connection).
This feature is based on libnetfilter-conntrack and is disabled by default and must be configured with the --enable-connmarktos flag to be used.
ss-redir : …
> mechanisms to set TOS/DSCP on the outgoing ciphered connections

- debian/shadowsocks-libev.postinst
The commit https://github.com/shadowsocks/shadowsocks-libev/commit/f32ac38c2f7aab09ec25131209954957518de42a allows to use `pwgen` to generate the initial password at the first installation.
However it won't work when `apg` isn't installed because:
* the `postinst` script has the errexit option set (`set -e`)
* at the first installation of ss-libev, `apg` or `pwgen` needs to be called to generate the initial password in config.json
* when `apg` isn't installed, `pathfind apg` would return 1
* and the `postinst` script will immediately exit due to `set -e`
This commit temporarily turn off the errexit option when running `pathfind`.
Below is my logs of tracking this issue down (by manually installing a deb I built):
```
root@trag:~# dpkg -i shadowsocks-libev_3.0.3-1_amd64.deb
Selecting …
```
> Turn off errexit option when detecting the apg command

- src/manager.c
- src/manager.h
Hello,
I tried to add options ```method, fast_open, mode, plugin, plugin-opts``` to ss-manager.
So that we can ```add: {"method": "aes-256-gcm", "server_port": "12345", "fast_open": true, "plugin": "obfs-server", "plugin_opts": "obfs=http", "mode": "udp_only"}``` now.
Parameter ```server_port``` and ```password``` are still necessary, and others are optional.
> Add method, fast_open, mode, plugin options to ss-manager

- debian/config.json
6d9732a changes the "method" parameter in the debian/config.json
from "rc4-md5" to "chacha20-ietf-poly1305". rc4-md5 is unsafe and
there is support for a better AEAD ciphersuite.
> Update the ciphersuite `method` in debian/config.json.

- src/server.c
When ss-server wrapped in a plugin server, every peer_name are 127.0.0.1, black list seems not working.
If large requests sent from the plugin server, ss-server would in DoS.
Maybe when in plugin mode, disable black list in ss-server and move it to plugin server?
> avoid blocking requests from local plugins server

- CMakeLists.txt
- src/CMakeLists.txt
Add a option in CMakeLists.txt for switch build with static libraries or not.
When you don't have static libraries, run with "cmake -DWITH_STATIC=OFF".
This is useful when you trying use QtCreator to browse the project.
> cmake option for skip static libraries check or not.

- src/local.c
Many users wants to do bypass with geoip:
https://github.com/shadowsocks/shadowsocks-libev/issues/78
https://github.com/shadowsocks/shadowsocks-libev/issues/564
So users are limited to Firefox and some few apps that using a local resolve.
But if we can resolve the domain then the geoip works for all situations.
This can be recognized as a user-behavior-leak but only users who using ACL will be affected, but it truly helps people who want a easier way to balance speed and traffic.
Maybe at least we can add an option to enable this.
> resolve domain so we can bypass domain with geoip

- src/local.c
- src/socks5.h
When handling a method select request, the number of methods is interpreted as a signed char. A malicious client could send a request with nmethods < 0, leading to all kinds of disastrous consequences.
Also, there is no reason to interpret the fields in SOCKS5 messages as signed.
> Fix handling of method select requests

- src/stream.c
If the first packet is less than nonce length, then the chunk nonce data will be overwrote by next packet and result in decrypt failed
> Fix decryption failed issue by nonce overwrite

- src/stream.c
If nonce received in more than one packet under some network condition, the salsa20 cipher decryption will lose cipher->nonce_len - left_len bytes of data.
> Fix losing data issue of SALSA20 cipher

- scripts/build_deb.sh
simple-obfs is released to debian unstable, and its git repo
is moved to alioth.
So update the URL of git repo and branch accordingly.
> Update simple-obfs git repo and branch

- src/jconf.c
- src/jconf.h
- src/redir.c
Add an option 'disable_sni' in the config file to allow clients running
ss-redir to disable the HTTP/SNI feature
As proposed here https://github.com/shadowsocks/shadowsocks-libev/issues/1503 , the option will disable the http/sni feature in ss-redir, keeping the default behaviour (sni enabled by default)
Don't know if a mention in the ascii doc, or if a command line argument are needed
> ss-redir: Add option to disable SNI feature

- src/netutils.c
- src/netutils.h
The ``<sys/socket.h>`` header should be included in ``src/netutils.h``
before the usage of ``struct sockaddr_storage``, otherwise build failed
with errors such as:
```
In file included from udprelay.c:53:0:
netutils.h:68:22: error: 'struct sockaddr_storage' declared inside parameter list [-Werror]
int ipv6first);
^
netutils.h:68:22: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]
```
Tested on DragonFly BSD 4.9-development and Debian Linux testing.
> Move <sys/socket.h> inclusion to fix build on DFlyBSD

- src/redir.c
As suggested in the previous pull request.
> ss-redir: fix memleak in remote_send_cb

- docker/alpine/Dockerfile
- docker/alpine/README.md
alpine/Dockerfile: add a new `ARGS` environment variable to pass additional arguments.
```shell
docker run -e PASSWORD=password -e ARGS='-6' shadowsocks-libev
```
https://github.com/wacky6/shadowsocks-libev/commit/5059a0cdef19aa25f42df89f047e5d0bf7a95437
> Add ARGS env variable to alpine Dockerfile

- src/local.c
- src/redir.c
Currently, ipv6_first entry in config is effective only for ss-server, but not for ss-local and ss-redir. Also no other config entry can enable ipv6 first option for ss-local or ss-redir.
> Fix: ss-local and ss-redir should also respect ipv6_first.

- scripts/build_deb.sh
- Install libbloom-dev in backports repository.
- Clone libsodium git under "libsodium" directory.
- Change to a safer way to check debhelper version.
- Remove simple-obfs for jessie/stretch because it's just
accepted to backports repository.
> Minor fix for build_deb.sh script

- src/udprelay.c
Two functions `construct_udprealy_header` and `parse_udprealy_header`
contained typos and should be `construct_udprelay_header` and
`parse_udprelay_header` respectively. This PR updates these function
names and the respective callers.
> Replace `udprealy` function name typos with `udprelay`.

- src/redir.c
DSCP value was directly applied to TOS.
Conversion op has been lost when porting the feature from 2.5 to 3.0.
> redir: fix dscp to tos conversion

- src/crypto.c
- src/redir.c
- src/server.c
In a few places `malloc` was being used without checking the return for
a `NULL` pointer. There's already a wrapper (`ss_malloc`) in
`util.c` that performs this check and exits if it fails so this PR
replaces the unsafe `malloc`s with `ss_malloc`s.
> Replace unchecked `malloc` with `ss_malloc`.

- src/ss-nat
It's useful to be able to specify an alternative LAN interface, like `br0`.
> ss-nat: Specify LAN interface with -I flag

- src/acl.h
Add missed package: ca-certificates, automake, libmbedtls-dev. 
Fix these errors:
- **ca-certificates missed**
fatal: unable to access 'https://github.com/shadowsocks/shadowsocks-libev.git/': Problem with the SSL CA cert (path? access rights?) 
- **automake missed**
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.   
autoreconf: failed to run aclocal: No such file or directory
- **libmbedtls-dev**
checking for mbedtls_cipher_setup in -lmbedcrypto... no
configure: error: mbed TLS libraries not found.
> Add missed package for Ubuntu Docker image building

- src/acl.c
Currently, there is a 255-character limit on ACL rules. A long ACL rule will be broken into several different rules, leading to surprising behaviors.
For example, there is an regular expression in the GFW List that is more than 900 characters, describing Google's various country specific domains. Making it a `proxy_list` ACL item:
[bypass_all]
[proxy_list]
google\.(ac|ad|ae|al|am|as|at|az|ba|be|bf|bg|bi|bj|bs|bt|by|ca|cat|cd|cf|cg|ch|ci|cl|cm|co.ao|co.bw|co.ck|co.cr|co.id|co.il|co.in|co.jp|co.ke|co.kr|co.ls|co.ma|com|com.af|com.ag|com.ai|com.ar|com.au|com.bd|com.bh|com.bn|com.bo|com.br|com.bz|com.co|com.cu|com.cy|com.do|com.ec|com.eg|com.et|com.fj|com.gh|com.gi|com.gt|com.hk|com.jm|com.kh|com.kw|com.lb|com.ly|com.mm|com.mt|com.mx|com.my|com.na|com.nf|com.ng|com.ni|com.np|com.om|com.pa|com. …
> Discards long ACL lines

- README.md
- scripts/build_deb.sh
libsodium 1.0.13 is current in Debian apt repository of:
- stretch-backports
- jessie-backports-sloppy
> Update README and build_deb since libsodium 1.0.13 is backported

- rpm/SOURCES/systemd/shadowsocks-libev.default
- rpm/SPECS/shadowsocks-libev.spec.in
This change includes:
1. Move shared library `shadowsocks-libev.so.*` to an package `libshadowsocks-libev`
and rename package `shadowsocks-libev-devel` to `libshadowsocks-libev-devel`
to reconcile with the deb packages.
2. Add a new package `shadowsocks-libev-zsh-completion`.
3. Run `setcap` after installation (similar to #1119).
4. Remove ss-nat because it is designed for OpenWrt/LEDE.
5. Auto restart instantiated services after update and stop/disable instantiated
services after uninstallation.
> Refine SPEC for RPM packages

- debian/control
Removed dependency libudns-dev, added libc-ares-dev
> Fixed Debian Package Control

- src/local.c
- src/socks5.h
* close the connection if the client doesn't speak SOCKS5
* check if client supports "no auth. required"
> ss-local: properly handle SOCKS5

- src/local.c
listen_ctx.remote_num will be greater than actual memory allocated in listen_ctx.remote_addr when bot plugin enabled and multi remote servers configured, which will cause a dereference in create_remote.
> fix segment fault when plugin enabled and multi remote servers configured

- src/local.c
- src/redir.c
- src/server.c
- src/tunnel.c
If no_delay is set to 1, recv_ctx->connected never gets set to 1.
Currently, recv_ctx->connected is only checked for the purpose of disabling NO_DELAY, so the problem fixed by this patch is entirely benign. Future modifications to shadowsocks might find some other use for recv_ctx->connected, however.
> always set recv_ctx->connected

- README.md
The command will be terminated if the parameter `-y` isn't following in ubuntu 16.04 TLS. (The command following will not executed when pasting the command queue of "[installing from PPA](https://github.com/shadowsocks/shadowsocks-libev#install-from-repository) for Ubuntu 14.04 and 16.04 users" into ssh terminal.)
> A minor change to let it getting on automatically

- docker/alpine/Dockerfile
Alpine 3.7 libtool pkg depends on bash pkg, this caused the compile hangs at "checking that generated files are newer than configure...", after check [this thread](https://forums.docker.com/t/problem-of-hanging-autoreconf/41015/3), I remove libtool and it works.
> Remove libtool to fix alpine 3.7 docker bug

- src/local.c
- src/shadowsocks.h
- src/udprelay.c
* Adds a Shadowsocks library interface to start `ss-local` with a callback. The function is called with the SOCKS server and UDP relay listen file descriptors. This is mainly for use in sandboxed iOS and macOS applications, where it is not possible to start `ss-local` as a process.
* Fixes an off-by-one bug in udp_relay that would result in a crash when LIB_ONLY is enabled.
* Supersedes #1829.
> LIB_ONLY improvements

- tests/aes-ctr.json
- tests/aes-gcm.json
- tests/aes.json
- tests/chacha20-ietf-poly1305.json
- tests/chacha20-ietf.json
- tests/chacha20.json
- tests/rc4-md5.json
- tests/salsa20.json
8388 is already taken by default config, so for test suites it's
better to choose a different port.
> tests: Change the port to listen from 8388 to 8389

- CMakeLists.txt
- src/CMakeLists.txt
Add a new option, WITH_EMBEDDED_SRC, which default is ON and same as
current setting.
When set to OFF, it can use system's libcork, libcorkipset, and libbloom.
It can be built in debian by:
$ cmake -DUSE_SYSTEM_SHARED_LIB=1 -DWITH_STATIC=OFF -DWITH_EMBEDDED_SRC=OFF
$ make
> Make cmake to build under Debian

- rpm/SOURCES/systemd/shadowsocks-libev.service
ss-server waits for local ip ready, add network-online.target here.
my env.
CentOS Linux release 7.2.1511 (Core)
orig. file doesnt work and failed on ip binding. add "network-online.target" to the after list. it works.
I guess it's not a generic issue, Im running centos 7.2 x64 vps. so I didnt replace "network.target" to  "network-online.target", keep the both items.
> update  shadowsocks-libev.service

- .dockerignore
- docker/alpine/Dockerfile
* Use the repository as context, instead of released .tar.gz
* Remove version information from Dockerfile, and let Docker Cloud handle it
* Add .dockerignore
Next steps:
1. Connect repository in Docker Cloud
2. Setup automated builds:
- A push on `master` branch triggers build for `unstable` tag
- A tag matching `/^v[0-9]+(\.[0-9]+){2}$/` triggers build for a same-named tag
Refer to #1914
> Update Dockerfile to utilize Docker Cloud auto build

- docker/alpine/Dockerfile
- docker/alpine/README.md
This PR aims to close #1914.
- `rng-tools` is installed as a runtime dependency to suppress the warning at start.
- Unnecessary `git submodule update` is removed from Dockerfile as it is done by Docker Cloud.
- Environment variable `SERVER_PORT` is removed from Dockerfile as the `EXPOSE` clause can't be changed at runtime and the customization of the port must be done by means of the `-p` argument of `docker run`.
- Descriptions in README.md are updated to match the usage of the auto-built images.
- Instructions on customizing the runtime arguments are added to README.md.
- Myself is added to the maintainer list of Dockerfile.
As for the Docker Cloud autotest, I didn't succeed in making it work. I think I'll close #1914 without it.
> Follow-ups of the migration to Docker Cloud

- README.md
- doc/shadowsocks-libev.asciidoc
- doc/ss-redir.asciidoc
* Add information on Docker image to `/README.md`
* Fix line indentation of usage in `/README.md`
* Remove unnecessary note about `ss-redir` in `/README.md`
* Remove prompt 'root@Wrt:~#' from code example for better consistency, in both `/README.md` and manpages
> Document improvments

- configure.ac
- docker/mingw/Dockerfile
- docker/mingw/Makefile
- docker/mingw/build.sh
- docker/mingw/deps.sh
- docker/mingw/prepare.sh
- src/Makefile.am
- src/aead.c
- src/crypto.c
- src/crypto.h
- src/json.c
- src/local.c
- src/netutils.c
- src/netutils.h
- src/plugin.c
- src/resolv.c
- src/resolv.h
- src/server.c
- src/stream.h
- src/tls.c
- src/tunnel.c
- src/udprelay.c
- src/utils.c
- src/utils.h
- src/winsock.c
- src/winsock.h
This pull request re-adds support for building against MinGW-w64. It also includes a Dockerfile in `docker/mingw` for easy compilation with Docker.
The main reason is that I found an efficient way to use **libev** library on Windows. With the support of [piscisaureus/wepoll](https://github.com/piscisaureus/wepoll) project by @piscisaureus, we can finally use efficient IOCP events instead of `select()`. So we can also enable building `ss-server` on Windows. There are still some minor issues with LSP (Layered Service Provider) support in wepoll (see piscisaureus/wepoll#5). Many applications use LSP, such as Proxifier or some game accelerators, and may interfere with wepoll. The current [patch](https://github.com/linusyang92/libev/commit/93499c3dbfb79c8a8fb378dce1f3e47b14a4ef85) is working …
> Re-add MinGW compilation support

- docker/mingw/deps.sh
- docker/mingw/prepare.sh
Please refer to discussion at shadowsocks/shadowsocks-libev/pull/1962.
This patch updates libcork submodule to support MinGW build and also modifies the Docker scripts to support build using official mbedtls releases.
The docker script will work when shadowsocks/libev#3 is merged into a new branched called `mingw`.
> Fix MinGW build using Docker

- README.md
- docker/mingw/make.bat
Add a Batch file `make.bat` in `docker/mingw` for Windows Docker users. Now one can simply double-click `make.bat` to build MinGW ports on Windows.
> Simplify Docker build on Windows

- configure.ac
- src/local.c
- src/local.h
- src/resolv.c
- src/server.c
- src/server.h
- src/winsock.c
- src/winsock.h
As we have an efficient MinGW port at the moment, how about adding TCP Fast Open  (TFO) support on Windows?
Let me start the discussion here in this pull request. Please **do not merge it** until it is fully reviewed. This patch needs more tests.
To build this patch with Docker, you need to edit `docker/mingw/build.sh` and run `make` or `make.bat`:
1. Change `git checkout ${PROJ_REV}` into **`git checkout pr`**.
2. Add one line **before** `git checkout pr`: **`git fetch origin pull/1965/head:pr`**
TFO is **only** supported on Windows 10, **1607** or later version (the earliest supported OS version should be [Build 14393](https://github.com/shadowsocks/shadowsocks-windows/blob/53ec77901c91d7f273ca4b35ad54de45353103db/shadowsocks-csharp/Util/Util.cs#L280)). So this patch will not benefit …
> Support TCP fast open on Windows

- README.md
Add some notes about TCP Fast Open on Windows and how to disable aggressive fallback on 1709 or later version.
> Documentation about TFO on Windows

- README.md
- docker/mingw/Makefile
- docker/mingw/build.sh
- docker/mingw/make.bat
- src/local.c
- src/plugin.c
- src/plugin.h
- src/server.c
- src/tunnel.c
- src/utils.h
- src/winsock.c
- src/winsock.h
This patch implements the SIP003 multi-process plugin model on Windows/MinGW, which depends on a port of subprocess.c in libcork that uses native Windows functions for spawning or killing subprocesses. The plugin side does not need any patch and can work seamlessly. Both client and server with simple-obfs have been tested to work.
The patch follows the standard POSIX behavior that the child process will exit if the main process quits normally/abnormally in advance. To notify the parent process when the child process (i.e. plugin process) exits, due to lack of SIGCHLD signal on Windows, this patch uses a workaround similar to the idea of SIP003. The main process picks another random TCP port (only bound to loopback) for communication with plugin process. When plugin exits unexpectedly, the …
> Support Plugins on Windows/MinGW

- docker/mingw/Dockerfile
- docker/mingw/build.sh
Update libcork submodule to support the plugin feature of MinGW port (see #1978). Also fixed a minor bug in Docker build script when plugin build is disabled.
> Update libcork and Docker script for MinGW

- src/local.c
Fix an issue that closes the plugin watcher socket in library only mode.
> MinGW: fix socket closing in wrong place

- docker/mingw/build.sh
- docker/mingw/deps.sh
- src/utils.h
- src/winsock.c
- src/winsock.h
Now we can also have nice colored text in Windows console just like other platforms. This patch also fixes some minor things, including docker script and error message handling.
> MinGW: Support colored text in Windows console

- src/local.c
Steps to reproduce: (1) Run `start_ss_local_server` in a background thread. (2) Start an arbitary child process in the main process. When the child process terminates, shadowsocks will terminate unexpectedly, printing log `plugin service exit unexpectedly`.
Shadowsocks listens for `SIGCHLD` of its plugin processes, if shadowsocks is running in a thread instead of a separate process, `SIGCHLD` sent for other receivers will be processed by shadowsocks, and may cause the problem above.
Since plugin is not supported in library usage (according to `profile_t` in `shadowsocks.h`), I think we can simply ignore the signal.
> Ignore SIGCHLD for library usage

- docker/alpine/Dockerfile
Add variable SERVER_PORT back, it can be customized with -e and be able to run multiple containers, or we may use -e ARGS="-p xxx" and that makes the cmd having 2 -p arguments.
Remove EXPOSE in the Dockerfile, as we always use -p to expose ports in docker run.
> Optimize Dockerfile, add SERVER_PORT back

- .gitignore
- Makefile.am
- configure.ac
- rpm/Makefile.am
- rpm/genrpm.sh
The new `srpm` target can be handled by Fedora Copr for
automated builds. A `rpm` target is also added for alignment.
> Create srpm and rpm targets to the Autotools build

- src/resolv.c
C-ares creates up to two sockets per nameserver. With up to three nameservers
in resolv.conf this makes a max of six active sockets.
Having only one ev_io watcher resulted in closing watchers that were
still active, needlessly resulting in DNS timeouts.
> Fix DNS timeouts

- .copr/Makefile
- rpm/SPECS/shadowsocks-libev.spec.in
- rpm/genrpm.sh
- scripts/git_archive.sh
- scripts/git_version.sh
Follow-up of https://github.com/shadowsocks/shadowsocks-libev/pull/2039#issuecomment-388513175
Support using repository as srpm source for **SCM / make srpm** package in COPR [(example)](https://copr.fedorainfracloud.org/coprs/mcspr/shadowsocks-libev/package/shadowsocks-libev/)
genrpm.sh now builds srpm by default, but still can optionally (-b flag) create rpm using rpmbuild
> Fedora COPR support

- docker/alpine/docker-compose.yml
Current setting will cause following error: `ERROR: pull access denied for shadowsocks-libev, repository does not exist or may require 'docker login'`, this update fixes this.
> update image value.

- docker/mingw/build.sh
- docker/mingw/deps.sh
We can further speed up MinGW build by `make -j$(nproc)` to utilize all cores.
> Docker: speed up MinGW build by parallel make

- src/utils.c
Memory of userconf in src/utils.c:get_default_conf() only gets allocated
once, and will not be freed. It's used as static buffer.
This can avoid using PATH_MAX, which actually doesn't exist on certain
platforms.
Info:
- https://www.gnu.org/software/hurd/community/gsoc/project_ideas/maxpath.html
- https://www.gnu.org/software/hurd/hurd/porting/guidelines.html#PATH_MAX_tt_MAX_PATH_tt_MAXPATHL
> Fix of PATH_MAX for GNU/Hurd

- docker/alpine/Dockerfile
- docker/alpine/README.md
- docker/alpine/docker-compose.yml
I have refined the Dockerfile to use AEAD by default and support listen on IPv6.
The old PR was closed because it was mistakenly made from my master branch.
> Docker: Support for IPv6 host, set default encryption method to GCM.

- src/aead.c
- src/crypto.h
There is a known issue that mbedTLS does not implement AES-NI correctly.
https://github.com/shadowsocks/shadowsocks-libev/issues/2147
However the libsodium have support for AES-NI (although only for 256bit AES/GCM).
This PR makes the method `aes-256-gcm` use libsodium's implementation when it is available.
To: @madeye please kindly review my PR and provide your insights.
To: @xqdoo00o could you help me benchmark the performance on your machine along with the Go version?
> Use libsodium for `aes-256-gcm` when available.

- README.md
update `libsodium` to 1.0.16 since 1.0.13 is deleted from https://download.libsodium.org/libsodium/releases/
> update libsodium to 1.0.16 because 1.0.13 is deleted from official release site

- configure.ac
Fix the behaviour of --disable-connmarktos and --enable-connmarktos=no that enables the feature.
Signed-off-by: DUPONCHEEL Sébastien <sebastien.duponcheel@corp.ovh.com>
> configure: Fix --disable-connmarktos option behaviour

- src/server.c
- src/udprelay.c
It wil be useful when more than one `ss-server` run.
before:
`Nov 26 12:00:15 abc ss-server[25924]: [udp] cache hit: 1.1.1.1:443 <-> 2.2.2.2:12345`
`Nov 26 15:21:03 gyt ss-server[3914]: connect to google.com:443`
after:
`Nov 26 12:00:15 abc ss-server[25924]: [10000] [udp] cache hit: 1.1.1.1:443 <-> 2.2.2.2:12345`
`Nov 26 15:21:03 gyt ss-server[3914]: [10000] connect to google.com:443`
> add server port in log file

- src/local.c
- src/plugin.c
- src/redir.c
- src/server.c
- src/tunnel.c
Refine 68f885c271bf1c2fbe98cfcc98e75b48cde65045. Somehow I postponed this change for 8 months. Good job me!
This fix the cases when there is a space in plugin path, for whatever reason.
Also I think I prefer this to putting them in `SS_PLUGIN_OPTIONS`.
> Refine passing plugin args

- configure.ac
Fixes:
- http://autobuild.buildroot.org/results/22a28e8fd8182e1c908541dbc5b0ee087c3803e6
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> configure.ac: fix static build with netfilter_conntrack

- src/server.c
This commit makes plugin server running as the user given by `-a` argument.
It's useful for [v2ray-plugin](https://github.com/shadowsocks/v2ray-plugin) when certificate and/or key file for TLS method only can be accessed by specified user.
```
user@localhost:~$ ll /path/to/host.*
-rw------- 1 ss-libev ss-libev 1143 Jan 29 09:33 /path/to/host.cer
-rw------- 1 ss-libev ss-libev  241 Jan 29 09:33 /path/to/host.key
user@localhost:~$ sudo -b ss-server -p 4433 -k XXX -a ss-libev --plugin v2ray-plugin --plugin-opts "server;tls;cert=/path/to/host.cer;key=/path/to/host.key"
2019-02-03 19:39:24 INFO: plugin "v2ray-plugin" enabled
2019-02-03 19:39:24 INFO: initializing ciphers... chacha20-ietf-poly1305
2019-02-03 19:39:24 INFO: tcp server listening at 127.0.0.1:37429
2019/02/03 19:39:24 V2Ray 4.13 …
```
> Switch user before starting plugin server

- cmake/configure.cmake
- src/CMakeLists.txt
To build shadowsocks-libev on macOS by cmake:
1. need to set CMAKE_REQUIRED_INCLUDES to let check_include_files() find pcre
2. need to add sodium head file path to include directories
Assume both pcre and libsodium are installed by Homebrew.
> fix cmake build on macOS

- src/CMakeLists.txt
Since files in bin are binary executables, they shoud be installed with execute permission.
Before:
After:
> cmake: keep execute permission of files in bin directory

- CMakeLists.txt
1. change pkgconfig file installation path
2. When choose to not use embedded libcork, libipset and libboom, pass this flag to cmake/config.h.cmake, and let #cmakedefine take effect
3. fix empty version string output when building by cmake
So now many os distributions (e.g. archlinux's PKGBUILD) can choose to build packages by this:
```bash
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DWITH_STATIC=OFF -DWITH_EMBEDDED_SRC=OFF
make DESTDIR=/tmp/aaaa install
```
> cmake: fix for system shared libs building, version string

- CMakeLists.txt
- doc/CMakeLists.txt
1. fix a typo in comment of last pr
2. change man and doc installation path to be compliant with os distribution standard
Now:
> fix typo; change installation path of man and doc

- doc/CMakeLists.txt
Previously every time running `make` or `make install`, commands will be ran to generate man files and html files even if *.asciidoc is not changed at all.
> cmake: change to absolute path to avoid command running every time

- src/plugin.c
bzero(3) is an old BSD compatibility function, and have a separated header file strings.h. So memset(3) maybe a better choice.
> change from bzero(3) to memset(3) for better compatibility.

- debian/shadowsocks-libev-local@.service
- debian/shadowsocks-libev-redir@.service
- debian/shadowsocks-libev-server@.service
- debian/shadowsocks-libev-tunnel@.service
- debian/shadowsocks-libev.service
- rpm/SOURCES/systemd/shadowsocks-libev-local.service
- rpm/SOURCES/systemd/shadowsocks-libev-local@.service
- rpm/SOURCES/systemd/shadowsocks-libev-redir@.service
- rpm/SOURCES/systemd/shadowsocks-libev-server@.service
- rpm/SOURCES/systemd/shadowsocks-libev-tunnel@.service
- rpm/SOURCES/systemd/shadowsocks-libev.service
Shadowsocks is a socks5 proxy program. It should run after network connection. In the old settings, Shadowsocks runs after network.target is booted by systemd. But I think it is not correct. Running network.target just means that services for maintaining network adapters are running. It does not mean network adapters have got IP and accepted or sent network packets. In some scenarios, for example laptop PC with WLAN, if I set shadowsocks-libev-local service start after system boots, it maybe does not work. Systemd cannot make sure network connection is OK after network.target starts. So I think Shadowsocks-libev services should started after network-online.target.
> Change from network.target to network-online.target in systemd service files.

- src/cache.c
If 'tmp' isn't accessed, 0 is returned by the function anyway. This
is a duplicate case therefore is not needed.
> cache: Remove unused return from 'cache_key_exist'

- src/redir.c
The default encryption methods in doc and code for redir differ.
> Fix redir default cipher

- docker/alpine/Dockerfile
Set cap_net_bind_service on ss-* binaries so they can be bound to privileged ports without root.
Every modern container storage driver supports this, the ones that don't will simply ignore it.
> Set cap_net_bind_service for docker

- src/aead.c
Before patch, after one chunk decoded, we do a memmove.
After patch, after all complete chunk decoded, we do a memmove.
> Remove unnecessary memmove

- src/crypto.c
Maybe we should add this warning in shadowsocks-android as well?
> Warn users when using stream ciphers

- src/crypto.c
setup mbedtls_md_context_t with hmac disabled to save some memory.
> crypto: md5 hash works without hmac mode

- src/server.c
Server made a connection to remote, remote replied with that connection.
nf_conntrack module would check orig-dst and orig-src by default and find every connection that dst and src matches reply-src and reply-dst, respectively.
more information please refer to https://www.spinics.net/lists/netfilter/msg57842.html
As a result, src and dst should be swapped to make nf_conntrack find the connection.
> server: fix setTosFromConnmark typo

- src/aead.c
- src/ppbloom.c
ppbloom_add only checks current bloom filter not both PING PONG filters
This reverts commit 9ae59819bea2c82a53eb680a7e5983406022b462.
> Revert "ppbloom:remove unnecessay bloom_check"

- src/crypto.h
As in issue #2607 , we have PING PONG bloom filters.
if anyone is full, we reset the other one.
As a result, the full bloom filter would be checked 5e5 times at current setup.
before patch:
full bloom filter error rate before reset 1-(1-1e-6)^5e5=1-0.606=0.394
after patch:
1-(1-1e-10)^5e5=1-0.99995=5e-5
> crypto: lower bloom filter error rate

- src/ppbloom.c
init utilizes calloc which malloc and memset.
need cherry-pick commit of libbloom
> ppbloom: save free() and subsequent init() overhead

- tests/test.py
Currently the test script assumes the returned web page is always encoded in UTF-8, which might not be the case. It is likely that the real encoding is `ISO-8859-1` and that running the script under python3 will raise error:
```
< 
{ [11931 bytes data]
100 11923    0 11923    0     0   184k      0 --:--:-- --:--:-- --:--:--  187k
Traceback (most recent call last):
File "tests/test.py", line 106, in <module>
line = str(line, 'utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 1105: invalid start byte
```
This pull request makes no assumption on the returned data and send the raw output to stderr as `bytes`. This should allow the test script to finish successfully when `tests/test.py` is run by python3.
> tests/test.py: Make script compatible with python3

- docker/alpine/README.md
According to https://github.com/shadowsocks/shadowsocks-libev/commit/0f55830b1dde69559135cdf100aeaa5c5faa8d36
> readme(docker): remove "--fast-open"

- src/udprelay.c
hints is not used after initialized.
> updrelay: cleanup

- README.md
This can prevent `Too many open files` error from happening due to sandboxing.
Do note that classic mode is not recommended, however, the only way I can find to get around that is to run `snap run --shell shadowsocks-libev.ss-server` and tweak nlimits there, which does not seem to be a good solution. I do wonder if there is a better solution.
> Use classic mode to install shadowsocks-libev

- src/utils.c
free userconf since it is not needed any more if fall back to the system-wide config.
> Fix a tiny memory leak

- docker/alpine/Dockerfile
- docker/alpine/README.md
Hi,
Due to alpine's default timezone is a UTC which may give the wrong logs. I've added an ENV to set the correct timezone. 
* before
* after
> Add Dockerfile timezone, Update readme.

- CMakeLists.txt
- doc/CMakeLists.txt
- src/CMakeLists.txt
Since this project also generates shared libraries, it'd be great if it can be used as dependency of other CMake projects.
But currently it doesn't work because the CMakeLists.txt uses `CMAKE_SOURCE_DIR` and `CMAKE_BINARY_DIR` which always refer to the top-level project source/binary directories.
I changed these variables to `PROJECT_SOURCE_DIR` and `PROJECT_BINARY_DIR`. Now it works both ways, as standalone project and as a part of other projects. Ref (https://stackoverflow.com/questions/22214349/modify-cmake-source-dir)
I also fixed a bug [here](https://github.com/shadowsocks/shadowsocks-libev/blob/b9ce095ee70ca19cafac82da43afb9de2d4a02e7/CMakeLists.txt#L48). Variables should be encapsulated with `${...}` rather than`$(...)`.
In addition, `include_directories` properties are not set for …
> cmake: fix build issues when this project is built as dependency of other CMake projects

- debian/rules
Regression caused by commit [0d96da4].
> debian/rules: Fix #2675

- src/CMakeLists.txt
Seems you only added `LIB_ONLY` macro to static library and forgot about the dynamic library.
> Also apply LIB_ONLY for dynamic library, fix #2443

- completions/bash/ss-local
- completions/bash/ss-manager
- completions/bash/ss-redir
- completions/bash/ss-server
- completions/bash/ss-tunnel
- completions/zsh/_ss-local
- completions/zsh/_ss-manager
- completions/zsh/_ss-redir
- completions/zsh/_ss-server
- completions/zsh/_ss-tunnel
- doc/shadowsocks-libev.asciidoc
- doc/ss-local.asciidoc
- doc/ss-manager.asciidoc
- doc/ss-redir.asciidoc
- doc/ss-server.asciidoc
- doc/ss-tunnel.asciidoc
```bash
ciphers='rc4-md5 aes-128-gcm aes-192-gcm aes-256-gcm aes-128-cfb aes-192-cfb aes-256-cfb aes-128-ctr aes-192-ctr aes-256-ctr camellia-128-cfb camellia-192-cfb camellia-256-cfb bf-cfb chacha20-ietf-poly1305 xchacha20-ietf-poly1305 salsa20 chacha20 chacha20-ietf'
```
```zsh
ciphers='(rc4-md5 aes-128-gcm aes-192-gcm aes-256-gcm aes-128-cfb aes-192-cfb aes-256-cfb aes-128-ctr aes-192-ctr aes-256-ctr camellia-128-cfb camellia-192-cfb camellia-256-cfb bf-cfb chacha20-ietf-poly1305 xchacha20-ietf-poly1305 salsa20 chacha20 chacha20-ietf)'
```
```asciidoc
-m <encrypt_method>::
Set the cipher.
+
*Shadowsocks-libev* accepts 19 different ciphers:
+
aes-128-gcm, aes-192-gcm, aes-256-gcm,
rc4-md5, aes-128-cfb, aes-192-cfb, aes-256-cfb,
aes-128-ctr, aes-192-ctr, aes-256-ctr, bf-cfb, …
```
> Add `xchacha20-ietf-poly1305` to docs and completions

- .github/workflows/build.yml
fix #2719
before merge，should stop autobuild in docker hub (it may be overwrites). 
when next release, just tag new version, but have to tag `latest` too.
https://hub.docker.com/r/morlay/shadowsocks-libev/tags
> Fix workflow build to make docker release with tags or edge for master

- README.md
- completions/bash/ss-redir
- completions/zsh/_ss-redir
- doc/shadowsocks-libev.asciidoc
- doc/ss-redir.asciidoc
- src/jconf.c
- src/jconf.h
- src/redir.c
- src/utils.c
The current transparent proxy implementation of ss-redir is:
- tcp: redirect(dnat)
- udp: tproxy
> Now tcp tproxy also supports.
When udp transparent proxy is enabled, you need to set different rules in the mangle table (for udp tproxy) and nat table (for tcp redirect) of iptables. This is a bit troublesome and the rules are not easy to manage.
So I added tproxy incoming support for tcp, so I only need to set the rules of the iptables mangle table (tcp and udp).
In addition, in the earlier version of ip6tables (old Linux kernel), there is no nat table. But if you use the tproxy (tcp and udp) mode, you do not need to set any nat table rules, and the entire iptables rules look neater.
> Add TPROXY support for TCP (ss-redir)

- docker/alpine/Dockerfile
- docker/alpine/README.md
- docker/alpine/entrypoint.sh
this means we no longer have to hardcode the password in the docker-compose file, and can treat the file as configuration rather than a secret.
> added support for Docker secrets and password file in the Docker image

- .github/dependabot.yml
- .github/workflows/build.yml
https://github.com/crazy-max/ghaction-docker-buildx is ARCHIVED
need to use official Docker action instead.
`.github/dependabot.yml` is github dependences checker, which will open pr for dependency updates.
now just for github-actions.
see more https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates
build steps with the new workflow https://github.com/morlay/shadowsocks-libev/actions/runs/279598906
image published https://hub.docker.com/r/morlay/shadowsocks-libev
> bump workflow actions to docker official provided

- src/manager.c
#2738 
Adding those lines makes the manager to pass -i option to its servers
Recreating the issue,
the _systemctl status_ now shows the requested behaviour:
`Main PID: 16143 (ss-manager)
CGroup: /system.slice/shadowsocks.service
├─16143 /usr/local/bin/ss-manager -c /home/admin/ss/shadowsocks-libev/tests/salsa20.json --manager-address /tmp/manager.sock -i eno123 --executable /usr/local/bin/ss-server
└─16159 /usr/local/bin/ss-server --manager-address /tmp/manager.sock -f /home/admin/.shadowsocks/.shadowsocks_8001.pid -c /home/admin/.shadowsocks/.shadowsocks_8001.conf -t 60 -i eno123 -s 127.0.0.1
`
> Fix manager not passing -i option

- src/udprelay.c
> Fix "ERROR: [udp] remote_recv_bind: Address already in use" when multiple `reuse_port`-enabled `ss-redir` instances are listening on the same address

- README.md
libsodium 1.0.16 has been removed to the old release ,
> the url of libsodium 1.0.16 has been removed to the old release

- configure.ac
- src/Makefile.am
Use pkg-config to retrieve the dependencies of netfilter_conntrack
and avoid the following build failure when building statically:
```
configure:13096: /data/buildroot-test/instance-1/output-1/host/bin/x86_64-linux-gcc -o conftest -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os   -static -I/data/buildroot-test/instance-1/output-1/host/x86_64-buildroot-linux-uclibc/sysroot/usr/include -DPCRE_STATIC -pthread -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -static -L/data/buildroot-test/instance-1/output-1/host/x86_64-buildroot-linux-uclibc/sysroot/usr/lib conftest.c -lnetfilter_conntrack -lnfnetlink -lev  -lcares -lsodium -lmbedcrypto -lpcre  >&5
/data/buildroot-test/instance-1/output-1/host/opt/ext-toolchain/bin/../lib/gcc/x86_64-buildroot-linux-uclib …
```
> configure.ac: use pkg-config to find netfilter_conntrack

- src/redir.c
- src/tunnel.c
- src/udprelay.c
Free memory of ```server_ctx_t``` before exiting gracefully.
> Fix memory leak

- debian/shadowsocks-libev.service
There is a race condition between shadowsocks-libev.service and
systemd-resolved.service after reboot/on boot. The shadowsocks
service tries to start before the dns service is started properly
and fails showing the corresponding errors in the logs.
> Run systemd service after network is available (unit file fix)

- src/utils.c
The return value of open is -1 in case of an error (detected using Synopsys Coverity Scan)
> fix check for return value of open when redirecting to null device

- src/plugin.c
Close socket when error occurs to avoid memory leak (detected using Synopsys Coverity Scan)
> Fix memory leak in get_local_port

- src/manager.c
freeaddrinfo fix in create_and_bind needs to be applied in create_server_socket (detected using Synopsys Coverity Scan)
> apply memory leak fix for create_and_bind to create_server_socket

- src/manager.c
properly terminate string which recvfrom does not do (detected using Synopsys Coverity Scan)
> properly terminate string which recvfrom does not do

- src/manager.c
fix order of tests to avoid strstr on NULL value (detected using Synopsys Coverity Scan)
> fix order of tests to avoid strstr on NULL value

- src/local.c
- src/redir.c
- src/server.c
- src/tunnel.c
- src/udprelay.c
Set `{listen,server}_sock` to `-1` when needed as already done in `src/manager.c` by commit ecf1fcc84594b09ed2d61e3677cd8e62bd897ccb to avoid the following build failure:
```
local.c: In function 'create_and_bind':
local.c:218:12: error: 'listen_sock' may be used uninitialized in this function [-Werror=maybe-uninitialized]
218 |     return listen_sock;
|            ^~~~~~~~~~~
```
Fixes:
- http://autobuild.buildroot.org/results/27471a878ff52a972ac087d534e44fb0c50808f6
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> fix maybe-uninitialized errors

- docker/alpine/entrypoint.sh
Hi! First of all, thank you for maintaining this amazing tool.
Overriding the image's default `$DNS_ADDRS` with an empty string still adds the `-d` option to the command.
Make sure that we only add the `-d` option if `$DNS_ADDRS` is defined and not empty.
> fix: being able to use empty DNS_ADDRS with docker image

- src/local.c
- src/netutils.h
- src/redir.c
- src/server.c
- src/tunnel.c
Mainlined MPTCP on Linux 5.6+ is enabled with IPPROTO_MPTCP rather than setsockopt.
Fixes shadowsocks/shadowsocks-libev#2883
> Fix --mptcp on kernels with mainlined MPTCP.

- .copr/Makefile
fix copr build issue caused by git CVE-2022-24765
> fix .copr build

- .gitignore
- src/udprelay.c
ref shadowsocks/shadowsocks-rust#855
When receiving UDP packets from remote servers, Redir will have to
create transparent sockets to bind() on those target addresses and then
relay data back to the local client. Target addresses may be IPv4 or
IPv6 addresses, so we may have to create that transprent sockets based
on the target addresses' family.
The most simpliest and easiest way is to always create IPv6 sockets and
converts IPv4 binding addresses and peer addresses to IPv4-mapped-IPv6.
> Redir UDP send back sockets should always be IPv6

- src/jconf.c
- src/local.c
- src/netutils.h
- src/redir.c
- src/server.c
- src/tunnel.c
- src/utils.c
- src/utils.h
Since 1630764b02bbcbf0980d8080ea6ee8fd9b2cabf0 shadowsocks-libev has gained the ability to make use of upstream MPTCP if available. Let's improve on that a bit, and figure out the way to enable MPTCP at runtime, rather than at build time.
Difference between MPTCP kernels is explained at https://github.com/multipath-tcp/mptcp_net-next/wiki#upstream-vs-out-of-tree-implementations
Procfs path difference are seemingly explained in mptcpd tests, at https://github.com/intel/mptcpd/blob/master/tests/test-mptcpwrap
So use IPPROTO_MPTCP on negative `mptcp` variable value, and tolerate absence of that constant at build time.
> Detect kernel support for MPTCP at runtime

- .copr/Makefile
Copr build for fedora 36 fails because submodule dirs are not in git safe.directory variable. Just add them explicitly, without fancy stuff like "git submodule foreach".
> Add submodules to git safe.directory for .copr build

- rpm/SPECS/shadowsocks-libev.spec.in
Building rpm on fedora 36 fails with ENOENT on libshadowsocks-libev.la. This happens because .la files now get automatically removed from buildroot. Assuming someone needs that .la file, opt out of the change, as described in "How To Test" section of the linked page.
> Fix rpm build for fedora 36

- configure.ac
- src/CMakeLists.txt
Recently builds on MinGW start to fail with undefined symbol errors:
```
[ 49%] Linking C executable ../bin/ss-server.exe
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/11.2.0/../../../../lib\libcares.a(ares__addrinfo_localhost.c.obj):(.text+0x1fe): undefined reference to `GetUnicastIpAddressTable@8'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld.exe: C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/11.2.0/../../../../lib\libcares.a(ares__addrinfo_localhost.c.obj):(.text+0x360): undefined reference to `FreeMibTable@4'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/11.2.0/../../../../i686-w64-mingw32/bin/ld.exe: …
```
> Fix build on MinGW

- README.md
221: You should jump this section and install them from distribution repository instead. -> You should jump to this section and install them from the distribution repository instead.
FIX #7
> fixes grammatical errors in README.md

- README.md
I tried to build from source on Ubuntu 22.04 LTS today and found `https://tls.mbed.org/download/` link is broken. Also I ran into errors when executing `./autogen.sh`, `error: possibly undefined macro: AC_MSG_ERROR`. `apt install pkg-config` fixes the error and built successfully.
> update MbedTLS dependency link and add Debian / Ubuntu apt pkg-config

- m4/mbedtls.m4
- src/aead.c
- src/crypto.c
- src/crypto.h
- src/stream.c
MbedTLS have released its new stable version 3.6 since Mar 28 this year. Many linux distributions are switching to it now. Shadowsocks-libev build fails with mbedtls3.0+ version. https://github.com/shadowsocks/shadowsocks-libev/issues/2868
This issue stops distributions such as debian from migrating to mbedtls3.6.
Since this is a bug-fix only port, I hope to be able to fix this problem upstream.
Some of the reasons for the changes can be found here: https://github.com/fw876/helloworld/issues/1504
@madeye
> Fix build with mbedtls3.6
