shadowsocks/shadowsocks-libev

libev/ev.c
Reference: http://svnweb.freebsd.org/ports/head/devel/libev/files/patch-ev.c?view=markup
=> Enable kqueue(2) on FreeBSD

docker/Dockerfile, docker/README.md, docker/entrypoint
* based on ubuntu image
* builds shadowsocks-libev from latest code
* more information can be found in README.md
Shadowsocks-compatible JSON configuration file is not supported in this version. Further discussion is required regarding that.
=> Dockerization

src/local.c, src/server.c, src/tunnel.c, src/utils.c, src/utils.h
抱歉，刚刚发了一个错误的pull request。
做了一些改动，以前当我把stderr指向一个文件的时候，会把vt100指令也写进文件，现在进行了isatty的检查，不会把vt100指令写入文件。
=> Add isatty check when change STDERR_FILENO to a file

src/server.c
fix  bug: 
initialize ciphers... (null)
listening at (null):8388
=> output bugs

src/redir.c, src/server.c, src/tunnel.c
Add use /etc/shadowsocks/config.json for ss-redir ss-server ss-tunnel
=> Add use /etc/shadowsocks/config.json for ss-redir ss-server ss-tunnel

configure, m4/mbedtls.m4
Check cipher availability before compiling.
=> Add more mbed TLS cipher check

Makefile.am, ss-local.1, ss-manager.1, ss-redir.1, ss-server.1, ss-tunnel.1
This commit contains rearranged man pages for shadowsocks-libev and the
five executables.
Please check if there is any mistake.
=> add newly arranged man pages

debian/shadowsocks-libev.default, debian/shadowsocks-libev.service
=> make Debian systemd service use /etc/default conf.

src/local.c
this should fixed working for some proxy client
=> try to recover socks5 connection on buggy proxy client

src/encrypt.c
Tested with mbed TLS v2.1.3.
API refer to : https://tls.mbed.org/api/md_8c_source.html Line 225, 413 and 140
=> use mbed TLS provided sha1-hmac function

src/common.h, src/local.c, src/server.c
Python 的我这里也搞好了，但是一方面不清楚 Python 版 ss 的维护情况，另一方面不确定用 C 扩展合不合适
总之代码在：
https://github.com/crvv/tcp_fastopen_darwin
https://github.com/crvv/shadowsocks
=> OS X 10.11 上的 fastopen

README.md, man/shadowsocks-libev.8, man/ss-local.1, man/ss-manager.1, man/ss-redir.1, man/ss-server.1, man/ss-tunnel.1
* Fix typo in man/ss-manager.1
* Update cipher information in README and man page
* Add `-n` option in man page
* Remove trailing spaces in README.md
* Add information about using mbedTLS in README.md
* Other minor enhancement
=> Various documentation update.

src/android.c
This PR reduce battery usage on shadowsocks-android. Companion commit: https://github.com/shadowsocks/shadowsocks-android/commit/6bff4f1a441ee83dca7f71da5f062c80fcc24681
=> Reduce battery usage - transmit traffic stat with binary

README.md
=> Update README on PPA not always being the latest version

docker/alpine/Dockerfile, docker/alpine/docker-compose.yml, docker/ubuntu/Dockerfile
+ expose UDP port
* bump up server version to 2.4.5.
=> Update docker related files.

src/redir.c
It's now output messages while redirecting.
This is useful at the time building up a router.
=> fix `ss-redir -v`.

man/shadowsocks-libev.8, man/ss-local.1, man/ss-manager.1, man/ss-redir.1, man/ss-server.1, man/ss-tunnel.1, src/local.c, src/manager.c, src/redir.c, src/server.c, src/tunnel.c, src/utils.c
- all 5 apps supports cli option '-h' without error exit code
- supports long option '--help'
=> updated cli option 'help'

man/shadowsocks-libev.8, man/ss-redir.1, src/udprelay.c
=> updated friendly IP_TRANSPARENT fatal message [part #2]

src/utils.c
=> clarify encrypt method info

README.md
=> Add NixOS and Nix to the TOC section of readme

debian/shadowsocks-libev-local@.service, debian/shadowsocks-libev-redir@.service, debian/shadowsocks-libev-server@.service, debian/shadowsocks-libev-tunnel@.service, debian/shadowsocks-libev.service
Referred:
https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Documentation=
=> Add manpage to systemd service file

README.md
Add information about `shadowsocks-libev` packages in official Debian repository.
=> update README for Debian installation

Makefile.am, configure.ac
=> fix disable-documentation option

debian/.gitignore, debian/control, debian/rules
* Fix d/control dependency
* Add --disable-ssp in d/rules and depend on dpkg-buildflags
=> Update debian package script

debian/copyright, debian/install, debian/rules, debian/shadowsocks-libev.docs, debian/shadowsocks-libev.install, debian/shadowsocks-libev.postinst, debian/shadowsocks-libev.postrm, debian/source.lintian-overrides
Changes:
- Add license of manpages to copyright
- Change way to handle config file (config.json)
- Add lintian-overrides
- Rename/Update docs and install file
=> Sync debian/ folder with version 2.4.7+20160630+ds-2

src/manager.c
Info:
- https://www.gnu.org/software/hurd/community/gsoc/project_ideas/maxpath.html
- https://www.gnu.org/software/hurd/hurd/porting/guidelines.html#PATH_MAX_tt_MAX_PATH_tt_MAXPATHL
=> fix of PATH_MAX for GNU/Hurd

src/encrypt.c, src/manager.c, src/server.c, src/shadowsocks.h, src/udprelay.c
=> Fix typo (found by codespell)

doc/shadowsocks-libev.asciidoc, doc/ss-local.asciidoc, doc/ss-manager.asciidoc, doc/ss-redir.asciidoc, doc/ss-server.asciidoc, doc/ss-tunnel.asciidoc, src/utils.c
=> Add AES-CTR ciphers info

docker/alpine/Dockerfile
```
checking for pcre location... not found
configure: error: Cannot find pcre library. Configure --with-pcre=DIR
```
=> fix a dependency error in Dockerfile

libcork/core/allocator.c, libcork/core/error.c, libcork/core/gc.c, libcork/core/ip-address.c, libcork/core/mempool.c, libcork/ds/array.c, libcork/ds/bitset.c, libcork/ds/buffer.c, libcork/ds/file-stream.c, libcork/ds/hash-table.c, libcork/ds/managed-buffer.c, libcork/ds/ring-buffer.c, libcork/include/libcork/config/config.h, libcork/include/libcork/config/version.h, libcork/include/libcork/core/allocator.h, libcork/include/libcork/core/api.h, libcork/include/libcork/core/callbacks.h, libcork/include/libcork/core/mempool.h, libcork/include/libcork/os/subprocess.h, libcork/include/libcork/threads/atomics.h, libcork/include/libcork/threads/basics.h, libcork/posix/env.c, libcork/posix/exec.c, libcork/posix/files.c, libcork/posix/process.c, libcork/posix/subprocess.c, libcork/pthreads/thread.c
Add back mingw/cygwin fixes compare to #855 
=> Update libcork to 0.15.0

src/encrypt.c
to get rid of self written code and make it clean.
Official doc: https://download.libsodium.org/doc/generating_random_data/
=> Switch random generator to libsodium's

src/acl.c, src/acl.h, src/server.c, src/utils.c
It requires root permission and only works on Linux platform.
=> Drop FIN packets to misbehaving clients

completions/bash/ss-local, completions/bash/ss-manager, completions/bash/ss-redir, completions/bash/ss-server, completions/bash/ss-tunnel
I think it's the time to support for bash completion.
Options are based on the output of `--help`. Maybe some of them are missing or redundant.
=> Add bash completion files

completions/bash/ss-local, completions/bash/ss-manager, completions/bash/ss-redir, completions/bash/ss-tunnel
=> Bash completion: add missing cipher list

doc/shadowsocks-libev.asciidoc, src/jconf.c, src/jconf.h, src/local.c, src/manager.c, src/redir.c, src/server.c, src/tunnel.c
Add this option like the Python version.
=> add `user` config option

src/uthash.h
=> Update uthash to latest

src/netutils.c, src/redir.c, src/resolv.c, src/server.c, src/tunnel.c, src/udprelay.c, src/utils.c
=> zeroize some structs before using

src/encrypt.c, src/local.c, src/manager.c, src/redir.c, src/resolv.c, src/server.c, src/tunnel.c
=> memset zero before using

src/local.c
In Mac OS X 10.10, `launch_activate_socket` was introduced.
So whenever the port is requested, the `launchd` can launch the program
dynamically. A possible plist may like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>Label</key>
<string>com.github.shadowsocks</string>
<key>ProgramArguments</key>
<array>
<string>/path/to/ss-local</string>
<string>-s</string>
<string>server host</string>
<string>-p</string>
<string>server port</string>
<string>-k</string>
<string>password</string>
<string>-m</string>
<string>method</string>
<string>-t</string>
<string>timeout</string>
<string>-A</string>
</array>
<key>Sockets</key>
<dict>
<key>Listeners</key>
<dict> …
```
=> support mac os x's launch_activate_socket

debian/control, debian/shadowsocks-libev.postinst
=> Add capabilities for Debian Linux, so you can run ss-* as non-root.

src/manager.c
fix a stupid mistake may remain useless bound socks.
thx @junsen.
=> fix bug in ss-manager when port reuse fail

README.md
=> Add instruction for build from source with CentOS 7

README.md
According to:
https://wiki.debian.org/DebianGeoMirror
=> Update debian mirror to httpredir

doc/ss-server.asciidoc
=> Fix duplicate text

README.md
Fix link inline readme.md  #1088
=> Update inline link for build from source with centos

README.md
Update ubuntu/debain package name
=> Update ubuntu/debain package name

README.md
This reverts commit 70e2cce07d7b489450a2e559e2148165deb440c7.
=> Revert "Update README.md (#1111)"

README.md
The README file has some missing command under Debian/Ubuntu
=> Fill the Debian apt command for readme

src/jconf.c
The json_null should be C NULL.
=> fixed json_null => NULL

src/aead.c, src/crypto.c, src/crypto.h
More details: https://github.com/shadowsocks/shadowsocks-org/issues/42
=> Add session key (SIP007)

scripts/deb4trusty.sh
For xenial script, it's clean enough so far.
=> Add more cleanup pkg to trusty script

debian/shadowsocks-libev.postinst
=> Add CAP_NET_ADMIN capability to ss-redir in postinst script

README.md, debian/copyright, scripts/build_deb.sh
Also include a few cleanup that simplified pkg installation from
backports repository.
=> Update build script to enable jessie/stretch etc

rpm/SPECS/shadowsocks-libev.spec.in, rpm/genrpm.sh
``BuildRequires`` and ``Requires``  for ``mbedtls-devel`` and ``libsodium-devel`` need to update.
=> pack submodules for genrpm

scripts/build_deb.sh
Also includes fixes for yakkety.
=> Update build_deb.sh to add libbloom support

scripts/build_deb.sh
- Use "lsb_release -cs" command to get distro info.
- Limit xz memory usage to 128MiB.
- Other minor fixes.
Fix #1300
=> Cleanup build_deb.sh script

scripts/build_deb.sh
Also add usage help and a few code cleanup
=> Make build_deb.sh script to build libraries and binaries separately

scripts/build_deb.sh
Confirmed under xenial and jessie-backports.
Other distro still need some work, but should be similar.
=> Add kcptun package build support to build_deb.sh script

README.md
1. update libsodium and mbedtls version
2. remove some duplicate information
3. move some building suggestion to other part of document
=> Readme refine

src/crypto.c
=> fix header

completions/zsh/_ss-local, completions/zsh/_ss-manager, completions/zsh/_ss-redir, completions/zsh/_ss-server, completions/zsh/_ss-tunnel
Hello,
I wrote some simple zsh-completion scripts.
=> Add zsh completion scripts

src/manager.c, src/manager.h
@madeye 
Sorry for this ...
I didn't notice that server was released in remove_server. It's my fault ...
I've tried this commit on macOS, ubuntu 16 and debian 8.
Sorry again about that ...
=> fix shadowsocks/shadowsocks-libev#1408

.travis.yml
Faster booting with "sudo : required"...Newer environment (i.e. higher GCC version) for more stable builds.
=> Improve Travis

src/local.c
Problem:
When a domain isn't exists in the domain ACL list, the domain will be resolved.
But when the ip of that domain is bypassed, the domain will be resolved again.
Now domain will be resolved only once.
Also fix some alignment problem of `err`.
=> aviod twice resolving when domain with ip bypassed

src/manager.c
=> Fix incorrect json configuration file

src/manager.c
This will be helpful to list the port:password combinations for easy management.
=> Add list API to list service ports

acl/gfwlist.acl
Since some part of this website "Bahamut" is blocked by China.And it benefits to many gamers and anime lovers.So I decide to list it into the GFW.
=> Add TW website "Bahamut"

docker/alpine/Dockerfile
=> delete duplicate code

src/local.c
The bug fix is in this commit: https://github.com/45G/shadowsocks-libev/commit/ba349a0dc8154bea83e55d91e8eea94800aa58b2
Further, I replaced 4 with request_len, where appropriate.
=> socks 5 request parsing: more suggestive code + small bugfix

.travis.yml
=> trigger macOS build

README.md
=> update Libsodium version

scripts/build_deb.sh
- Update build of libsodium to use debian's git repo
- Now libbloom is available in stretch-backports and
jessie-backports-sloppy
=> Update scripts/build_deb.sh after stretch release

src/utils.h
Signed-off-by: Xingwang Liao <kuoruan@gmail.com>
=> Redirect 'INFO' log to stdout

README.md, cmake/configure.cmake, configure.ac, src/Makefile.am, src/local.c, src/netutils.c, src/redir.c, src/resolv.c, src/resolv.h, src/server.c, src/server.h, src/tunnel.c, src/udprelay.c, src/udprelay.h
Replace libudns with libc-ares as per some security concerns.
=> Add c-ares support

scripts/build_deb.sh
Thanks to Tom <hexuxin@foxmail.com> for the bug report.
=> Fix scripts/build_deb.sh for debian jessie

tests/test.py, tests/test.sh
Set default dns to 8.8.8.8 for tests/test.py
=> tests: Update default dns setting in tests

src/common.h, src/local.c, src/redir.c, src/server.c, src/tunnel.c, src/utils.c, src/utils.h
This pull request implements feature request #1921. It works.
=> Search XDG_CONFIG_HOME for user-specific config

src/plugin.c
=> Invoke plugins direct instead of using "sh".

src/http.c
Refer: https://github.com/dlundquist/sniproxy/commit/4af9a1b62b7987f2e9f3c561f589c10092d4e150
=> Fix https://github.com/shadowsocks/shadowsocks-libev/issues/1945

README.md
New section in README.md to show how to build MinGW port using Docker.
=> Add instruction of building MinGW port in Readme

.dockerignore, docker/alpine/Dockerfile
* Image size optimization
* Run with `exec` so `Ctrl - C`  works
* Fix runtime error: missing dependencies
* Dockerfile format adjustments
=> Docker: optimizations

cmake/configure.cmake, doc/CMakeLists.txt
=> fix cmake syntax.

scripts/build_deb.sh
- Use https URL when possible.
- Use salsa git repo instead of alioth (anonscm) for those already
migrated in debian.
=> scripts/build_deb.sh: Update URL in script

src/manager.c, src/netutils.c, src/server.c
gcc (GCC) 8.0.1 20180324 (Red Hat 8.0.1-0.20)
修改后使用此版本编译通过，且可以正常使用
=> Fix Build Fail with GCC8

tests/aes-ctr.json, tests/aes-gcm.json, tests/aes.json, tests/chacha20-ietf-poly1305.json, tests/chacha20-ietf.json, tests/chacha20.json, tests/rc4-md5.json, tests/salsa20.json, tests/test.sh
Fix tests by using "local" setting instead of "local_address" in config.
This is mentioned in:
- https://github.com/shadowsocks/shadowsocks-libev/issues/247
=> Update config under tests/ folder

doc/shadowsocks-libev.asciidoc, doc/ss-manager.asciidoc, doc/ss-server.asciidoc, docker/alpine/Dockerfile, docker/alpine/README.md, src/manager.c, src/manager.h
Refer: https://github.com/shadowsocks/shadowsocks-libev/issues/2116
=> Multipe nameservers support

README.md, src/tunnel.c, src/tunnel.h
`delayed_connect_cb` is not used here because it adds latency to normal connections. 
TODO:
=> TCP Fast Open support for ss-tunnel

doc/ss-manager.asciidoc
Update the document about traffic statistics and the response from 'ping' massage.
=> update the document about ss-manager

src/local.c
Just realized my previous commit wouldn't work when using local address 0.0.0.0 to serve socks connections over the network. This should fix it.
=> Make local address 0.0.0.0 work with udp relay

src/android.c, src/local.c
See also: https://github.com/shadowsocks/shadowsocks-android/pull/2070
=> Specify stat_path on Android

src/local.c
Fixes https://github.com/shadowsocks/shadowsocks-android/issues/2078.
=> Allow long direct TCP connections

src/ss-nat
Tested with busybox and gnu coreutils.
=> Fix a bug introduced in #2230, and some improvements

src/local.c
* Make this program even more verbose in verbose logging mode.
* Print error about missing option instead of printing a long usage text, if any required option is missing.
=> Make ss-local(1) more verbose in verbose mode

src/manager.c
解决ss-manager中使用stat命令没有成功和失败的回显
=> Add echo for stat API

src/server.c
=> Allow long idle connections in server

README.md
Just updated FreeBSD section of README.md, make it easier to read and follow.
=> Update FreeBSD section in README.md

src/aead.c, src/ppbloom.c
bbloom_add and bbloom_check are in fact the same function.
let's make bbloom_add return collision information.
=> ppbloom:remove unnecessay bloom_check

src/redir.c, src/udprelay.c
make tos setup working at ipv4 and ipv6
=> refine tos setsockopt in redir and udprelay

src/udprelay.c
I believe you left one more line to change with 4214894f5dd9408601a72c05c3c9469a75ce77f4.
=> Fix sockopt level.

README.md
Reverts shadowsocks/shadowsocks-libev#2626
=> Revert "Use classic mode to install shadowsocks-libev"

README.md
I'm no longer maintaining the packages for Fedora and RHEL. This PR seeks to remove this section to avoid confusions.
=> Remove the unmaintained Fedora COPR section

src/jconf.c, src/jconf.h, src/manager.c
Add ss-manager read manager_address argurment from config file
=> Add ss-manager read manager_address argurment from config file

.github/workflows/build.yml
=> added workflow for buildx

docker/alpine/Dockerfile
- Fix path error (buildx error)
=> Minor update

README_pt_BR.md
The goal is to expand the community by facilitating understanding for Brazilian developers. I checked to ensure the minimum of translation errors that could cause problems.
=> Translation of README.md into Brazilian Portuguese.
